#!/bin/bash

for mod in cdc_acm ftdi_sio; do
    path="/sys/module/$mod/parameters/no_dtr"
    if test -r $path; then
	if [ $# -gt 0 ]; then
	    echo "$1" > $path
	fi
	v="$(cat $path)"
	echo "$mod $v"
    else
	echo "$mod not loaded"
    fi
done
